#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\room.bof

BOFS =  barlqrm.bof crnthrm.bof jasperrm.bof kocarm.bof marnrm.bof tosrm.bof \
   ghall.bof godroom.bof razarm.bof badland2.bof castle1c.bof cave3.bof \
   dungeon.bof field1.bof bazmans.bof hermhut.bof monsroom.bof outgrace.bof \
   profroom.bof temple.bof tempkra.bof tempqor.bof temprii.bof castle2a.bof \
   castle2d.bof mockers.bof duke1.bof duke2.bof duke3.bof \
   univ.bof castle2e.bof gallery.bof bowhut.bof tpost1.bof tpost2.bof \
   rentroom.bof necarena.bof desert.bof qormasland.bof \
   championsroom.bof

!include $(KODDIR)\kod.mak
