#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wallelem.bof
BOFS =  wallfire.bof wallltng.bof poisfogc.bof web.bof asburstc.bof wallifire.bof fogcloud.bof boltflash.bof explosionboom.bof soundobject.bof fireflame.bof smoker.bof reflectflash.bof acidsplash.bof


!include $(KODDIR)\kod.mak